#ifndef HELLO_MOVEIT_HPP
#define HELLO_MOVEIT_HPP

#define POSITION_X 0
#define POSITION_Y 1
#define POSITION_Z 2
#define ORIENTATION_X 3
#define ORIENTATION_Y 4
#define ORIENTATION_Z 5
#define ORIENTATION_W 6

#endif 